const cafes = [
  {
    id: 1,
    name: "Ember Downtown",
    location: "422 Hearthstone Way, Central District",
    hours: "Open Daily: 7:00 AM - 9:00 PM",
    image: "/cafes/ember-down.jpg",
    tag: "Downtown",
    coordinates: { lat: 47.6062, lng: -122.3321 },
  },
  {
    id: 2,
    name: "Ember Uptown",
    location: "87 Kindling Street, Old Town",
    hours: "Open Daily: 7:00 AM - 9:00 PM",
    image: "/cafes/ember-up.jpg",
    tag: "Uptown",
    coordinates: { lat: 47.6205, lng: -122.3493 },
  },
  {
    id: 3,
    name: "Ember Roast",
    location: "15 Cinder Lane, Harbour Quarter",
    hours: "Open Daily: 6:30 AM - 8:00 PM",
    image: "/cafes/ember-roast.jpg",
    tag: "Roastery",
    coordinates: { lat: 47.6097, lng: -122.3422 },
  },
  {
    id: 4,
    name: "Ember Glow",
    location: "203 Maple Grove Avenue, Riverside",
    hours: "Open Daily: 7:30 AM - 10:00 PM",
    image: "/cafes/ember-glow.jpg",
    tag: "Glow",
    coordinates: { lat: 47.6587, lng: -122.3138 },
  },
  {
    id: 5,
    name: "Ember Hearth",
    location: "9 Birchwood Plaza, Garden District",
    hours: "Mon - Fri: 7:00 AM - 9:00 PM | Sat - Sun: 8:00 AM - 11:00 PM",
    image: "/cafes/ember-hearth.jpg",
    tag: "Hearth",
    coordinates: { lat: 47.6253, lng: -122.3222 },
  },
  {
    id: 6,
    name: "Ember Spark",
    location: "56 Flint Road, University Quarter",
    hours: "Open Daily: 6:00 AM - 8:30 PM",
    image: "/cafes/ember-spark.jpg",
    tag: "Spark",
    coordinates: { lat: 47.6553, lng: -122.3035 },
  },
  {
    id: 7,
    name: "Ember Smoke",
    location: "318 Ashfield Terrace, North End",
    hours: "Mon - Sat: 7:00 AM - 9:00 PM | Sun: Closed",
    image: "/cafes/ember-smoke.jpg",
    tag: "Smoke",
    coordinates: { lat: 47.6740, lng: -122.3866 },
  },
  {
    id: 8,
    name: "Ember Stone",
    location: "74 Coalbrook Street, West Market",
    hours: "Open Daily: 7:00 AM - 9:30 PM",
    image: "/cafes/ember-stone.jpg",
    tag: "Stone",
    coordinates: { lat: 47.5707, lng: -122.3870 },
  },
]

export default cafes